apiVersion: v1
kind: Service
metadata:
  name: bikrantsahoo-nodejsapp
spec:
  selector:
    app: bikrantsahoo-nodejsapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # The port your app listens on
  type: LoadBalancer
