name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/bikrantsahoo-nodejsapp:${{ github.sha }} .
        docker tag your-dockerhub-username/bikrantsahoo-nodejsapp:${{ github.sha }} your-dockerhub-username/bikrantsahoo-nodejsapp:latest

    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/bikrantsahoo-nodejsapp:${{ github.sha }}
        docker push your-dockerhub-username/bikrantsahoo-nodejsapp:latest

